# Generated by Django 3.2.25 on 2024-04-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('leaveSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('rollno', models.IntegerField()),
                ('phoneno', models.IntegerField()),
                ('fatherName', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=255)),
                ('hostelNumber', models.CharField(max_length=255)),
                ('roomNumber', models.IntegerField()),
                ('fromDate', models.DateField()),
                ('time', models.TimeField()),
                ('toDate', models.DateField()),
                ('reason', models.CharField(max_length=500)),
                ('parentContact', models.IntegerField()),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(-1, 'Pending'), (0, 'Rejected'), (1, 'Approved')], default=-1, null=True)),
                ('parent_responded', models.PositiveSmallIntegerField(blank=True, choices=[(-1, 'Pending'), (0, 'Rejected'), (1, 'Approved')], default=-1, null=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.role')),
            ],
        ),
        migrations.DeleteModel(
            name='applicationModel',
        ),
    ]
