# Generated by Django 3.2.25 on 2024-04-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveSystem', '0002_auto_20240405_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='fatherName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='fromDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='hostelNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='parentContact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='parent_responded',
            field=models.PositiveSmallIntegerField(choices=[(-1, 'Pending'), (0, 'Rejected'), (1, 'Approved')], default=-1),
        ),
        migrations.AlterField(
            model_name='application',
            name='phoneno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='rollno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='roomNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='semester',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(-1, 'Pending'), (0, 'Rejected'), (1, 'Approved')], default=-1),
        ),
        migrations.AlterField(
            model_name='application',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='toDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
