# Generated by Django 3.2.25 on 2024-04-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveSystem', '0003_auto_20240405_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='parent_responded',
            field=models.SmallIntegerField(choices=[(-1, 'Pending'), (0, 'Rejected'), (1, 'Approved')], default=-1),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Pending'), (0, 'Rejected'), (1, 'Approved')], default=-1),
        ),
    ]
