# Generated by Django 3.2.25 on 2024-04-05 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('leaveSystem', '0003_alter_applicationmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.role'),
        ),
    ]
