# Generated by Django 3.2.25 on 2024-04-05 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('leaveSystem', '0004_alter_applicationmodel_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='applicationModel',
            new_name='Application',
        ),
    ]
