# Generated by Django 3.2.25 on 2024-04-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveSystem', '0005_rename_applicationmodel_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='username',
        ),
    ]
