# Generated by Django 3.2.25 on 2024-04-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveSystem', '0006_rename_name_application_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(-1, 'Pending'), (0, 'Rejected'), (1, 'Approved')]),
        ),
    ]
