# Generated by Django 3.2.25 on 2024-04-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveSystem', '0008_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='parent_responded',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(-1, 'Pending'), (0, 'Rejected'), (1, 'Approved')], default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(-1, 'Pending'), (0, 'Rejected'), (1, 'Approved')], default=-1, null=True),
        ),
    ]
